os:
- osx
language: generic
osx_image: xcode9.1
install:
- bundle install
before_script:
- carthage update --platform iOS,macOS
script:
- bundle exec rake ci
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: aQXoIjuu3FFac15O2s2Q3RX3ueuKan5tDWl1y01/LldgHfqhqTaYw1x5ClyeMcX44WqjXn18LHOzIcBAVFFt48/d0zKcKiPbVfKZSondjCpB51C93Z2wEYjPxD6IyT3WV69ecSCT8x+JtXzwwtCc9bZ5+TdbXq3cnWp/Psf17IkEVwArEZY9AAQk3xIciL1g+B8Qkl+dP4Ui7nyBTo3ta4OoUjGmDeGEWiFA99NbV/RbieSEvcW72YpVM9tx1u7gswYNbaPhm/SwHGZmZ8mpBhesZHK1plOCAg6WovPq7LneYFmGF/YaRyi/tyUwExm1ERjxnEjoh8CMm1ctE+zT2HYbqP5iZvriLWom3Kd3yHziBQyFgaidm9mY7x6YeUWfGmWrqx3CFZJkw62oV4PEqmFiLzljBMit1yQXV6mGi0apTxdvKDNAVcz6TMSDyMVGY7JapMeKkR0NelS9jIExU4Y9qbzLdrcWqmaJYqIlO9QUUFBVPjPT7H3MUx5tlwr3nVAbpFwKwU5YrVgg4lePzqwpHGRLXfrl4mRqyHJqjYnFbjMxDTJiC9FQxyzYSpr5yII1zUYN1+/8N3cGbTK+DV4vvekfXHdf6Azq+KRd2Y2m/Sd6VqC5TM3eGpVIozyTLKpQzINLp8K9R/TaoVZuA+2M9iG1xHh0PTnIWi/qzNg=
